CREATE DATABASE IF NOT EXISTS clients;

USE clients;

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users(
id INT UNSIGNED PRIMARY KEY	AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
age INT UNSIGNED,
profession VARCHAR(20) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM users;